### ISSUE TITLE
CI/CD for aarch64

### ISSUE THREAD

**Issue by ceseo** [iovisor/ubpf#106]
I noticed the current Travis CI only runs for x86_64. What would be necessary for it to run for 64-bit Arm as well?

Thanks

**Comment by JiongWang** [comment]
Would be nice to have aarch64 backend integrated into the CI. Perhaps @Alan-Jowett could give Carlos some guides?

**Comment by Alan-Jowett** [comment]
You can run docker with qemu aarch64 emulation. As an example, using cbl-mariner as the distro:
```
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker run --rm --platform=linux/arm64 -it mcr.microsoft.com/cbl-mariner/base/core:2.0.20220426-arm64 /bin/bash
```

Then inside the docker container, run the tests.

**Comment by ceseo** [comment]
Actually, Travis CI supports arm64 for OSS projects. I posted PR #112 to add it to the current `.travis.yml` file.

**Comment by ceseo** [comment]
Closing. PR #112 merged.
