### ISSUE TITLE
Possible division bug in interpreter

### ISSUE THREAD

**Issue by dthaler** [iovisor/ubpf#139]
https://github.com/iovisor/ubpf/blob/main/vm/ubpf_vm.c#L241 correctly casts the divisor to unsigned.

However https://github.com/iovisor/ubpf/blob/main/vm/ubpf_vm.c#L355 does not.  inst.imm is declared as int32_t, so this looks like a bug.

Same bug in https://github.com/iovisor/ubpf/blob/main/vm/ubpf_vm.c#L388 for modulo.

**Comment by Alan-Jowett** [comment]
I can confirm that the behavior of uBPF matches the behavior of Linux JIT, so I believe the behavior is correct.
