### ISSUE TITLE
ubpf_jit_arm64.c fails under address sanitizer

### ISSUE THREAD

**Issue by Alan-Jowett** [iovisor/ubpf#150]
https://github.com/iovisor/ubpf/actions/runs/3223073458/jobs/5272772649

There are a series of address sanitizer warnings when performing JIT on ARM64. 

@matt-gretton-dann do you want to take look? If you don't have time, let me know and I can see if I can take care of it.

**Comment by matt-gretton-dann** [comment]
I will take a look.

**Comment by Alan-Jowett** [comment]
I narrowed it down to this list of locations:

```
/home/runner/work/ubpf/ubpf/vm/ubpf_jit_arm64.c:143:41:
/home/runner/work/ubpf/ubpf/vm/ubpf_jit_arm64.c:151:41:
/home/runner/work/ubpf/ubpf/vm/ubpf_jit_arm64.c:224:41:
/home/runner/work/ubpf/ubpf/vm/ubpf_jit_arm64.c:326:41:
/home/runner/work/ubpf/ubpf/vm/ubpf_jit_arm64.c:339:41:
/home/runner/work/ubpf/ubpf/vm/ubpf_jit_arm64.c:360:28:
/home/runner/work/ubpf/ubpf/vm/ubpf_jit_arm64.c:360:46:
/home/runner/work/ubpf/ubpf/vm/ubpf_jit_arm64.c:363:28:
/home/runner/work/ubpf/ubpf/vm/ubpf_jit_arm64.c:379:49:
/home/runner/work/ubpf/ubpf/vm/ubpf_jit_arm64.c:387:45:
```

A large number of them appear to be related to the following patter:
```
emit_instruction(state, (sixty_four << 31) | op | (0 << 21) | (0 << 5) | rd);
```
It appears as if this is 32bit wide bitmask that is being emitted here? Perhaps define it as a struct with explicit field widths:
```
typedef union _arm64_instruction {
    uint32_t raw;
    struct {
        int dest:5;
        int src:5;
        int imm : 12;
        int op_base:7;
        int op_ext:2;
        int width : 1;
    };
} arm64_instruction_t;
```
And then:
```
arm64_instruction_t inst = { .dest = rd, .src = rn, .imm = imm12, .op_base = 0x11, .op_ext = op, .width = sixty_four };
```
Personal preference I guess, but to me this is clearer.

**Comment by matt-gretton-dann** [comment]
This is caught by the undefined behaviour sanitizer - which was not in the list of sanitizers enabled by the old `Makefile`.  Hence why this has not been caught before.

The majority of the issues seem to be related to signed-ness and integer promotions, and may have found one or two actual bugs (although not silent-codegen faults).

I have historically not liked the union access trick as I believed it was undefined behaviour (writing one union member, reading another).  Although having just tried to find the appropriate quotes in the standards I think this may actually be a C++ rule not a C one.
