### ISSUE TITLE
Should we remove string table support in the JIT?

### ISSUE THREAD

**Issue by matt-gretton-dann** [iovisor/ubpf#164]
With the fix to how we handle division by zero (#115) neither JIT backends now make use of the string tables.  However, support remains in the code base - even though it is not executed (in some cases `#if 0`ed out).

The question is do we see the need for string table support to be resurrected in the future?  If we don't we can remove the current support.  If we do then we may still want to remove the current support as it will be a maintenance burden until we need it again.

**Comment by Alan-Jowett** [comment]
If we need the code in the future, it's always available in the git history. We should remove the dead code.

**Comment by matt-gretton-dann** [comment]
Closed by #165
