### ISSUE TITLE
Possible division by 0 in div32 instruction implementation 

### ISSUE THREAD

**Issue by joachimff** [iovisor/ubpf#229]
The div32 instruction in ubpf_vm.c checks if the value of the source register is different from 0 before performing the division on the whole value. However, this approach may result in a division by 0 if the value of the register has bits set on the high 32 bits and 0 on the low.

To prevent this issue, I propose modifying the conditional check before the division to only consider the low 32 bits of the register's value. This can be achieved by casting the value of the source register to an unsigned 32-bit integer before performing the check.

Here is the updated code for the div32 instruction:

```c
case EBPF_OP_DIV_REG:
    reg[inst.dst] = u32(reg[inst.src]) ? u32(reg[inst.dst]) / u32(reg[inst.src]) : 0;
    reg[inst.dst] &= UINT32_MAX;
    break;
```
ubpf_vm.c:318

With this change, the div32 instruction will only perform the division if the low 32 bits of the source register's value are non-zero, avoiding the possibility of a division by 0.

**Comment by Alan-Jowett** [comment]
Thanks @joachimff. This should be fixed now.
