### ISSUE TITLE
No install target in vm/Makefile

### ISSUE THREAD

**Issue by sbates130272** [iovisor/ubpf#30]
If other programs want to make use of libubpf.a it would be nice to have a make install target in the Makefile to put this .a and the associated ubpf.h in the appropriate places on the system.

**Comment by pchaigno** [comment]
I'd welcome a pull request implementing this change!

**Comment by sbates130272** [comment]
Just added a PR for this. See #31.

**Comment by pchaigno** [comment]
Closing as fixed in #31.
