### ISSUE TITLE
Add support for 32-bit jump instruction

### ISSUE THREAD

**Issue by dthaler** [iovisor/ubpf#354]
BPF_JA | BPF_JMP32

Documentation references:
* https://github.com/ietf-wg-bpf/ebpf-docs/pull/42
* https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/Documentation/bpf/standardization/instruction-set.rst?id=245d4c40c09bd8d5a71640950eeb074880925b9a

**Comment by Alan-Jowett** [comment]
Resolved by: https://github.com/iovisor/ubpf/pull/166
