### ISSUE TITLE
MAX_EXT_FUNCS seems to be too small

### ISSUE THREAD

**Issue by Officeyutong** [iovisor/ubpf#425]
Currently MAX_EXT_FUNCS is hardcoded in code and has a value of 64, see https://github.com/iovisor/ubpf/blob/39872ad471c206051407d89ab8ed62d9ba0d7310/vm/ubpf_vm.c#L33

This seems to be too small, since kernel has more than 200 helpers (see https://github.com/libbpf/libbpf/blob/master/src/bpf_helper_defs.h)

What about determining the maximum number of external helpers at runtime, and let user provide this number when calling ubpf_create?

**Comment by Alan-Jowett** [comment]
I believe the changes @hawkinsw made to add ubpf_register_external_dispatcher should now permit an arbitrary number of helper functions.
