### ISSUE TITLE
Missing support for atomic instructions

### ISSUE THREAD

**Issue by Officeyutong** [iovisor/ubpf#426]
There are atomic instructions in eBPF standard, but they seemed to be missing from ubpf

https://docs.kernel.org/bpf/standardization/instruction-set.html#id22

**Comment by Alan-Jowett** [comment]
@Officeyutong I think this should be fixed now? Please let me know if there are any missing instructions or please close this.

**Comment by Officeyutong** [comment]
Thank you!
