### ISSUE TITLE
ubpf won't operate in a Trusted Execution Environment (TEE) like OpenEnclave.

### ISSUE THREAD

**Issue by Alan-Jowett** [iovisor/ubpf#51]
Problem:
ubpf_compile relies on mmap and mprotect that are not supported in a TEE. 

Proposal:
Define new API: ubfp_translate that only does the translate/resolve and is called by ubpf_compile. 
ubpf_translate would have no dependency on mmap or mprotect and would be usable in a trusted execution environment. 
ubpf_translate would be passed a target buffer that it would translate into.

Justification:
Desire to move eBPF verifier / JIT code out if kernel into a TEE to improve stability of kernel and provide better isolation.

**Comment by jpsamaroo** [comment]
Going even further than just mmap/mprotect, I would argue that the core JIT translation machinery shouldn't make any syscalls at all, in the event that the JIT is being used in an embedded or restricted environment that does not allow them. This is especially relevant if we want to gain support for running a hypothetical 32-bit ARM JIT in a microcontroller environment, where we might not even be running an OS (I've done it before with the interpreter).

**Comment by Alan-Jowett** [comment]
I think the new function I added solves this:
https://github.com/iovisor/ubpf/blob/6492b7a9363ea1e32194a95b66617df0f7fd42de/vm/ubpf_jit_x86_64.c#L585

I propose closing this issue.
