### ISSUE TITLE
Is there support for ARM64 JIT compiler ?

### ISSUE THREAD

**Issue by shogun786** [iovisor/ubpf#55]
Wondering if there is any plan to support ARM64 JIT for ubpf ?

**Comment by jpsamaroo** [comment]
Not yet, there is only an x86_64 JIT right now. But an ARM64 (AArch64?) JIT would certainly be welcome.

**Comment by sbates130272** [comment]
Oh boy, I would LOVE one of these.

**Comment by matt-gretton-dann** [comment]
PR #99 is a draft PR which implements an ARM64 JIT.

**Comment by JiongWang** [comment]
@matt-gretton-dann Thanks for the work, PR #99 looks to be a good start for AArch64 JIT support, I tested it locally, passed uBPF builtin tests. Hope this could be merged.

Meanwhile, I kind of feel the string relocation and jump relocation could be unified and could share common data structure, this perhaps applies to both x86 and aarch64 backend and might be worth some follow up patches

**Comment by Alan-Jowett** [comment]
Closing this as the aarch64 JIT is now implemented and tested in CI/CD.
