### ISSUE TITLE
Running the test framework?

### ISSUE THREAD

**Issue by multi-stream** [iovisor/ubpf#60]
Is there instructions showing how to run the test framework?

**Comment by jpsamaroo** [comment]
From https://github.com/iovisor/ubpf/blob/master/.travis.yml:
```
# make sure to be in the ubpf top-level directory
make -C vm COVERAGE=1  # build vm
nosetests -v   # run tests
```

**Comment by multi-stream** [comment]
Good info! That works! Thanks!

**Comment by Alan-Jowett** [comment]
Can you try out the instructions I added in this PR https://github.com/iovisor/ubpf/pull/69?

**Comment by multi-stream** [comment]
Yes. Looks like it works.
From what I can see it should works with python3 too. I have not try it though.
