### ISSUE TITLE
uBPF uses 128 byte stack by default - Should this match the common consensus of 512 bytes

### ISSUE THREAD

**Issue by Alan-Jowett** [iovisor/ubpf#74]
uBPF uses 128 byte stack by default - Should this match the common consensus of 512 bytes?

Other projects (Linux, generic-epbf and others) all agree on a 512 byte stack size. Anyone know why uBPF has a default of 512?

**Comment by rlane** [comment]
Feel free to change the default to 512. I don't recall any specific reason for choosing 128.

**Comment by niclashedam** [comment]
I agree on this. I have gone ahead and created a PR for this (#75).
