### ISSUE TITLE
uBPF ubpf_exec should separate errors returned from the return value of the eBPF program

### ISSUE THREAD

**Issue by Alan-Jowett** [iovisor/ubpf#79]
uBPF ubpf_exec should separate errors returned from the return value of the eBPF program

Currently, ebpf_exec returns both errors from the eBPF program and return values from the eBPF program using the same 64bits. This makes it impossible to differentiate between failures in the eBPF program (divide by zero and out of bounds) from an eBPF program that returns -1.

**Comment by jpsamaroo** [comment]
I think it would make sense to leave the function return as the eBPF program return value, and add an extra `int *err` argument to `ubpf_exec` for passing errors. And maybe if it's set to `NULL` we can print the error to stderr instead?

**Comment by Alan-Jowett** [comment]
@jpsamaroo that sounds like a good idea, but I think it's probably best to constrain this to a single issue. Perhaps file a separate issue to track how both the jitted function and ubpf_exec handle returning error messages?
