### ISSUE TITLE
JIT stack allocation

### ISSUE THREAD

**Issue by simon-jouet** [iovisor/ubpf#9]
Hi everyone,

I've been doing few things with ubpf and ran into an issue yesterday with how the JIT load value to the stack. I'm not sure if it's something I'm doing that's wrong or a bug. I managed to modify the code to get it working locally but if it's a bug it would be nice to fix it :) and if it's something I'm doing wrong, it would be nice to know why!

First thing is the C code I'm using (compiled to bpf with clang). I modified the loader to do the map relocation from the elf and also added both map functions to the vm.

```c
int bpf_prog1(void *pkt)
{
        long index = 1;
        long insertvalue = 0xdeadbeefdeadbeef;
        long value;
        int ret;

        bpf_map_update_elem(&my_map, &index, &insertvalue, 0);

        value = (long)bpf_map_lookup_elem(&my_map, &index);

        return (int)value;
}
```

The issue was that once calling the bpf_map_update_elem the two pointers index and insertvalue were clearly valid pointers but not containing the values. So therefore what I was interested in was:
```
lddw r1, 0x1
stxdw [r10-8], r1
lddw r1, 0xdeadbeefdeadbeef
stxdw [r10-16], r1
```

Going through the jit compiled code with a debugger I noticed that the two values were allocated outside the stack and therefore calling the bpf_map_update_elem (call rax) was overriding the stack and I was losing the two values.

My fix is to modify ubpf_jit_x86_64.c at line 95 and to copy the stack pointer to R10 *before* the stack space is allocated and the pointer incremented by the STACK_SIZE.

```c
    /* Copy stack pointer to R10 */
    emit_mov(state, RSP, map_register(10));

    /* Allocate stack space */
    emit_alu64_imm32(state, 0x81, 5, RSP, STACK_SIZE);
```

Best regards,
Simon

**Comment by xuanyue0** [comment]
> First thing is the C code I'm using (compiled to bpf with clang). I modified the loader to do the map relocation from the elf and also added both map functions to the vm.

@simon-jouet That looks like code many of us will need :smiley: 
Would you be willing to contribute it back?

/cc @rlane

**Comment by rlane** [comment]
Sorry I missed this before. Please send a pull request if you have a chance.

**Comment by simon-jouet** [comment]
@xuanyue0 The code for the map relocation isn't the cleanest but I will push it on the fork I've got of ubpf so you can have a look. Regarding the map themselves, I've got two implementations for the time being, one where the kernel maps are called but in that case the prototype has to be slightly different (the data is copied back and forth user-space and kernel space, it's not the fastest ...) And a second implementation where I just brought the maps (array and hashtable) in userspace so it got nothing to do with the kernel anymore. The code will be on github at some point relatively soon, but I can't right now for some reasons

@rlane I will make a pull request for the stack fix later on today

**Comment by xuanyue0** [comment]
> The code for the map relocation isn't the cleanest but I will push it on the fork I've got of ubpf so you can have a look.

Thanks!

> Regarding the map themselves, I've got two implementations for the time being, one where the kernel maps are called but in that case the prototype has to be slightly different (the data is copied back and forth user-space and kernel space, it's not the fastest ...)

You probably can't share the details but why do need kernel maps if the BPF VM is in userspace??

**Comment by simon-jouet** [comment]
> You probably can't share the details but why do need kernel maps if the BPF VM is in userspace??

You don't it was just an easy way to bring the map in without having to recode it. The proper way to do it is the second way I did it by bringing the code in userspace but it requires slightly more dev. effort :). If you're interested I can discuss what I'm doing in private, just not here for the time being.

**Comment by xuanyue0** [comment]
@simon-jouet Sure, I'm xuanyue0 on freenode (I'm usually on the #github chan). You can also join me by mail.

**Comment by xuanyue0** [comment]
> And a second implementation where I just brought the maps (array and hashtable) in userspace so it got nothing to do with the kernel anymore. The code will be on github at some point relatively soon, but I can't right now for some reasons

@simon-jouet Do you know if you will be able to publish this soon? I have implemented the map relocations and am currently finishing the implementation of the arrays. If I can avoid reimplementing the hash tables from scratch, that'd be :+1:

**Comment by simon-jouet** [comment]
Hi @xuanyue0, hopefully in a month (I know it's quite a while but not much I can do about it). For the hash table implementation there isn't much point re-implementing it from scratch.

You can't really just reuse the hashtable from the kernel implementation because AFAIK the data structure is not available in userspace, but it's fairly trivial to use an existing hashtable implementation and write the few functions to deal with the lookup/insert ...

The only thing to deal with is the file descriptor, by default every kernel ebpf table is associated a file descriptor which doesn't make sense in a userspace application so you need to have some global index that points to the different instantiated tables.
